sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t lunchtm/rpi-test .
# test image
- docker run lunchtm/rpi-test uname -a
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "ENV MYSQL_VERSION" Dockerfile | awk 'NF>1{print $NF}')
    docker tag lunchtmi/rpi-test lunchtmi/rpi-test:$TAG
    docker push lunchtmi/rpi-test:$TAG
    docker push lunchtmi/rpi-test
  fi


